# Generated by Django 5.2 on 2025-05-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
