# Generated by Django 5.2 on 2025-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_task_created_at_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinboardmessage',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
